name: coffee_online_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  smooth_page_indicator: ^1.2.0+3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  equatable: ^2.0.5
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  flutter_secure_storage: ^9.2.2
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  bloc: ^8.1.4
  flutter_map: ^7.0.2
  flutter_rating_bar: ^4.0.1
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  agora_rtc_engine: ^6.3.2
  flame: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pics/coffee (3).png"

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
  assets:
  - assets/pics/coffee (0).png
  - assets/pics/coffee (1).png
  - assets/pics/coffee (2).png
  - assets/pics/coffee (3).png
  - assets/pics/coffee (4).png
  - assets/pics/coffee (5).png
  - assets/pics/coffee (6).png
  - assets/pics/path.png
  - assets/pics/broken-image.png
  - assets/pics/image-gallery.png
  - assets/pics/americano.png
  - assets/pics/cappuccino.png
  - assets/pics/flat_white.png
  - assets/pics/visa.png
  - assets/pics/master_card.png
  - assets/pics/fpx.png
  - assets/pics/mocha.png
  - assets/pics/ad_background.jpg
  - assets/icons/not_found.svg
  - assets/icons/clean.svg
  - assets/icons/setting.svg
  - assets/icons/take_away.svg
  - assets/icons/detect.svg
  - assets/icons/delete.svg
  - assets/icons/call.svg
  - assets/icons/message.svg
  - assets/icons/email.svg
  - assets/icons/locate.svg
  - assets/icons/keypad.svg
  - assets/icons/speaker.svg
  - assets/icons/volume_off.svg
  - assets/icons/exit_call.svg
  - assets/icons/send.svg
  - assets/icons/credit_card.svg
  - assets/icons/gift.svg
  - assets/icons/home.svg
  - assets/icons/delivery.svg
  - assets/icons/edit.svg
  - assets/icons/list.svg
  - assets/icons/ice.svg
  - assets/icons/some_ice.svg
  - assets/icons/many_ice.svg
  - assets/icons/carry.svg
  - assets/icons/hot.svg
  - assets/icons/cup.svg
  - assets/icons/buy.svg
  - assets/icons/inactive_cup.svg
  - assets/icons/active_cup.svg
  - assets/icons/profile.svg

