// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsjrinyhXXI58Or2nnuFBsDxhBKLCmeg',
    appId: '1:13590674188:web:13018cc6caf2426b496729',
    messagingSenderId: '13590674188',
    projectId: 'coffee-shop-445bb',
    authDomain: 'coffee-shop-445bb.firebaseapp.com',
    storageBucket: 'coffee-shop-445bb.appspot.com',
    measurementId: 'G-08RKWNW3YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXMURF9MDBFe-OOTTmC8FaFgZ0mSvW2Lk',
    appId: '1:13590674188:android:942389635650aa39496729',
    messagingSenderId: '13590674188',
    projectId: 'coffee-shop-445bb',
    storageBucket: 'coffee-shop-445bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEWAlbLaKLPuKFgsvUh6eS7Ubf2zGl9uo',
    appId: '1:13590674188:ios:a3e29a6536628719496729',
    messagingSenderId: '13590674188',
    projectId: 'coffee-shop-445bb',
    storageBucket: 'coffee-shop-445bb.appspot.com',
    iosBundleId: 'com.example.coffeeOnlineStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADsjrinyhXXI58Or2nnuFBsDxhBKLCmeg',
    appId: '1:13590674188:web:059c94eb27d3229b496729',
    messagingSenderId: '13590674188',
    projectId: 'coffee-shop-445bb',
    authDomain: 'coffee-shop-445bb.firebaseapp.com',
    storageBucket: 'coffee-shop-445bb.appspot.com',
    measurementId: 'G-98DVWNK880',
  );
}
